### PR TITLE
Updated to Robo 0.5

### PR DESCRIPTION
**Pull request by sjableka**
Robo 0.5 introduced some BC breaking changes (mostly by renaming classases/namespaces/etc.). This merge fixes these incompatibilites.

### CODE REVIEW

**Comment by PG2000** [comment]
Hey Codeception Team,

is it possible that you merge the pull request ?

**Comment by sjableka** [comment]
Ping @DavertMik

**Comment by raistlin** [comment]
@DavertMik May you merge and tag new version?

**Comment by miramir** [comment]
+1

**Comment by DavertMik** [comment]
yes, thanks for the update!

**Pull request merged**
