### PR TITLE
chore: Use lastest version of Robo #50

### PR DESCRIPTION
**Pull request by programadormarin**

### CODE REVIEW

**Comment by Luc45** [comment]
Hey. Are there plans for merging this? This package is currently not compatible with robo 2, therefore runs in some conflicts with some up-to-date symfony packages.

This would suffice for me: `consolidation/robo: ^1.0.0 || consolidation/robo: ^2.0.0`

**Comment by fkupper** [comment]
@DavertMik sorry to bother you directly. Any chances we can have this released?

**Comment by pjam** [comment]
Hello! 

I'm also interested that this gets merged. I want to update composer on my project, which needs symfony/process update, which needs consolidation/robo update to version 2.*.

Any impediments why this is not merged yet?

**Comment by DavertMik** [comment]
Implemented in #56

**Pull request closed without merging**
