### PR TITLE
Fix split by time

### PR DESCRIPTION
**Pull request by DavertMik**
Merged #29

### CODE REVIEW

**Comment by DavertMik** [comment]
@vansari could you take a look? 
I'm merging outdated PR, checking if it applies to your refactoring paradigm

**Comment by vansari** [comment]
Hi @DavertMik 

I will check it this evening. 
Reminder to myself: answer quicker 😁

At a first look I miss the tests... But I will try to create them.

**Comment by DavertMik** [comment]
Thanks, @vansari 
Yeah.. Tests are the problem :) 
Could you check this Extension. 
This feature seems to be very useful but I don't have any project for parallel testing to try it

**Comment by vansari** [comment]
Hi @DavertMik,
I have found some issues in the Branch. I work on a fix and let you know if I'm ready.

**Comment by DavertMik** [comment]
Thanks!

**Comment by vansari** [comment]
Hi @DavertMik 

Do you know what's wrong with the composer check?! Should we recreate the composer.lock? (run composer update)

**Comment by DavertMik** [comment]
@vansari Hi, composer json was updated but now tests fail. I can't figure out what's wrong...

**Comment by vansari** [comment]
Hi @DavertMik 

I will check it this evening. I will also update the readme. 

Thanks a lot.

**Pull request merged**
