### PR TITLE
split by time task

### PR DESCRIPTION
**Pull request by ivan1986**
split tests to groups by execution time
one long test to one group and many fast tests to other groups

### CODE REVIEW

**Comment by DavertMik** [comment]
Wow. That's an awesome feature. I'm so sorry I noticed it so late

**Comment by DavertMik** [comment]
Not sure why tests fail. Ok, I should look into it

**Comment by roseofgold** [comment]
Has this been abandoned? This feature would help me out greatly.

**Comment by ivan1986** [comment]
@roseofgold try to rebase and run, maybe all works

**Pull request closed without merging**
